# Generated by Django 5.1.6 on 2025-02-21 22:14

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30, unique=True)),
                ('item_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
